all:
	@echo Enter VAR name
VAR6: clean
	gcc keypad.c -o keypad_v6 -D VAR6 -lbcm2835
VAR8: clean
	gcc test.c -o keypad_asp -D VAR8 -lbcm2835
VAR10: clean
	gcc keypad.c -o keypad_v10 -D VAR10 -lbcm2835
clean:
	rm -f *.o
